name: 🐍 Snake animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: snake
  cancel-in-progress: true

jobs:
  generate:
    name: Generate & publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake SVG
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#000000&color_dots=#ffffff,#cccccc,#999999,#555555,#000000
            dist/github-contribution-grid-snake-dark.svg?color_snake=#ffffff&color_dots=#0d1117,#4d4d4d,#808080,#b3b3b3,#ffffff

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
